import = [
   "~/.config/alacritty/themes/themes/github_dark.toml"
]

[font]
size = 12.0

[font.bold]
family = "CaskaydiaMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[shell]
program = "/bin/zsh"
args = ["-c", "tmux new -As0"]
